namespace PicoNode.Agent.Domain;

[PicoSerializable]
[PicoPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[PicoDerivedType(typeof(LlmCreated), "LlmCreated")]
[PicoDerivedType(typeof(LlmUpdated), "LlmUpdated")]
[PicoDerivedType(typeof(LlmDeleted), "LlmDeleted")]
[PicoDerivedType(typeof(SystemLlmPromoted), "SystemLlmPromoted")]
[PicoDerivedType(typeof(SystemLlmDemoted), "SystemLlmDemoted")]
[PicoDerivedType(typeof(AgentCreated), "AgentCreated")]
[PicoDerivedType(typeof(LlmChanged), "LlmChanged")]
[PicoDerivedType(typeof(ThinkingLevelSet), "ThinkingLevelSet")]
[PicoDerivedType(typeof(MaxTokensSet), "MaxTokensSet")]
[PicoDerivedType(typeof(ThinkingEnabledSet), "ThinkingEnabledSet")]
[PicoDerivedType(typeof(ToolAdded), "ToolAdded")]
[PicoDerivedType(typeof(ToolDescriptionUpdated), "ToolDescriptionUpdated")]
[PicoDerivedType(typeof(ToolRemoved), "ToolRemoved")]
[PicoDerivedType(typeof(AgentRenamed), "AgentRenamed")]
[PicoDerivedType(typeof(SkillLearned), "SkillLearned")]
[PicoDerivedType(typeof(KnowledgeAccumulated), "KnowledgeAccumulated")]
[PicoDerivedType(typeof(SystemPromptEvolved), "SystemPromptEvolved")]
[PicoDerivedType(typeof(AgentDeleted), "AgentDeleted")]
public abstract record DomainEvent : IDomainEvent;
