<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>PicoJsonRpc.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rpc\PicoJsonRpc\PicoJsonRpc.csproj" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="Fixtures\**"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
