using PicoNode.Actor.Abs;

namespace PicoNode.Agent.Domain;

[PicoSerializable]
[PicoPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[PicoDerivedType(typeof(AgentCreated), "AgentCreated")]
[PicoDerivedType(typeof(AgentStarted), "AgentStarted")]
[PicoDerivedType(typeof(AgentCompleted), "AgentCompleted")]
[PicoDerivedType(typeof(AgentFailed), "AgentFailed")]
[PicoDerivedType(typeof(LlmSwitched), "LlmSwitched")]
[PicoDerivedType(typeof(LlmAdded), "LlmAdded")]
[PicoDerivedType(typeof(LlmRemoved), "LlmRemoved")]
[PicoDerivedType(typeof(ToolAdded), "ToolAdded")]
[PicoDerivedType(typeof(ToolDescriptionUpdated), "ToolDescriptionUpdated")]
[PicoDerivedType(typeof(ToolRemoved), "ToolRemoved")]
[PicoDerivedType(typeof(ChildSpawned), "ChildSpawned")]
[PicoDerivedType(typeof(ThinkingLevelSet), "ThinkingLevelSet")]
[PicoDerivedType(typeof(AgentRenamed), "AgentRenamed")]
[PicoDerivedType(typeof(SkillLearned), "SkillLearned")]
[PicoDerivedType(typeof(SkillRefined), "SkillRefined")]
[PicoDerivedType(typeof(KnowledgeAccumulated), "KnowledgeAccumulated")]
[PicoDerivedType(typeof(SystemPromptEvolved), "SystemPromptEvolved")]
[PicoDerivedType(typeof(AgentDeleted), "AgentDeleted")]
[PicoDerivedType(typeof(SessionStarted), "SessionStarted")]
[PicoDerivedType(typeof(MessageAppended), "MessageAppended")]
[PicoDerivedType(typeof(LeafMoved), "LeafMoved")]
[PicoDerivedType(typeof(SessionRenamed), "SessionRenamed")]
[PicoDerivedType(typeof(SessionDeleted), "SessionDeleted")]
public abstract record DomainEvent : IDomainEvent;
