using System.Net;
using PicoDI;
using PicoDI.Abs;
using PicoNode.Web;
using PicoWeb;

var container = new SvcContainer();
container.RegisterScoped<PicoWeb.Samples.Controllers.UsersController>();
container.RegisterScoped<PicoWeb.Samples.Controllers.ProductsController>();
container.RegisterScoped<PicoWeb.Samples.Controllers.PostsController>();
container.Build();

var app = new WebApp(container);

// ── Controller endpoints (generated by Controllers.Gen) ──
EndpointRegistrar.RegisterAll(app);

// ── Inline endpoints ──
app.MapGet("/api/health", static (WebContext ctx, CancellationToken _) =>
    ValueTask.FromResult(WebResults.Json(200, """{"status":"ok"}""", "OK")));

// ── Landing page ──
var wwwroot = Path.Combine(AppContext.BaseDirectory, "wwwroot");
app.Use(new StaticFileMiddleware(wwwroot).InvokeAsync);

// ── Start ──
var server = new WebServer(
    app,
    new WebServerOptions { Endpoint = new IPEndPoint(IPAddress.Loopback, 7004) }
);
await server.StartAsync();
Console.WriteLine($"Listening on {server.LocalEndPoint}");
await Task.Delay(Timeout.Infinite);
await server.DisposeAsync();
