using System.Net;
using PicoDI;
using PicoDI.Abs;
using PicoNode.Web;
using PicoWeb;

// ── PicoWeb Sample — DI First WebAPI ────────────────────
//
// Demonstrates:
//   1. MapGet/MapPost inline lambda endpoints (exact + parameterized)
//   2. Controllers/ folder convention (auto-discovered by Controllers.Gen)
//   3. AOT-safe DI with RegisterScoped<T>() — PicoDI.Gen generates registrations
//   4. AOT publish: dotnet publish -c Release -r win-x64 -p:PublishAot=true --self-contained

var container = new SvcContainer();
container.RegisterScoped<PicoWeb.Samples.Controllers.UsersController>();
container.Build();
var app = new WebApp(container);

// Controller endpoints (auto-generated by Controllers.Gen)
EndpointRegistrar.RegisterAll(app);

// Diagnostic endpoints
app.MapGet("/api/health", (WebContext ctx, CancellationToken _) =>
    ValueTask.FromResult(WebResults.Json(200, """{"status":"ok"}""", "OK")));

app.MapGet("/api/echo/{msg}", (WebContext ctx, CancellationToken _) =>
{
    var msg = ctx.RouteValues.TryGetValue("msg", out var v) ? v : "";
    return ValueTask.FromResult(WebResults.Json(200, $$"""{"echo":"{{msg}}"}""", "OK"));
});

app.MapPost("/api/data/{key}", (WebContext ctx, CancellationToken _) =>
{
    var key = ctx.RouteValues.TryGetValue("key", out var v) ? v : "";
    return ValueTask.FromResult(WebResults.Json(200, $$"""{"key":"{{key}}"}""", "OK"));
});

// Start
var server = new WebServer(
    app,
    new WebServerOptions { Endpoint = new IPEndPoint(IPAddress.Loopback, 7004) }
);
await server.StartAsync();
Console.WriteLine($"Listening on {server.LocalEndPoint}");
await Task.Delay(Timeout.Infinite);
await server.DisposeAsync();
