namespace PicoWeb.Gen;

[Generator(LanguageNames.CSharp)]
public sealed class MapMethodGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var mapCalls = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => IsInvocationCandidate(node),
                transform: static (ctx, ct) => GetReturnType(ctx, ct)
            )
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        var collected = mapCalls.Collect();

        context.RegisterSourceOutput(collected, GenerateSource);
    }

    private static bool IsInvocationCandidate(SyntaxNode node)
    {
        if (
            node is InvocationExpressionSyntax invocation
            && invocation.Expression is MemberAccessExpressionSyntax memberAccess
            && (
                memberAccess.Name.Identifier.Text == "MapGet"
                || memberAccess.Name.Identifier.Text == "MapPost"
                || memberAccess.Name.Identifier.Text == "MapPut"
                || memberAccess.Name.Identifier.Text == "MapDelete"
            )
        )
        {
            return true;
        }
        return false;
    }

    private static string? GetReturnType(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        var semanticModel = ctx.SemanticModel;

        // Get the last argument (lambda or method reference)
        var lastArg = invocation.ArgumentList.Arguments.LastOrDefault();
        if (lastArg == null)
            return null;

        // Try to get the type from the lambda or delegate
        var typeInfo = semanticModel.GetTypeInfo(lastArg.Expression, ct);
        if (typeInfo.ConvertedType == null)
            return null;

        // If it's a lambda, find the return type
        if (lastArg.Expression is LambdaExpressionSyntax lambda)
        {
            // Walk the lambda body to find the return type
            if (lambda is SimpleLambdaExpressionSyntax simpleLambda)
            {
                var bodyType = semanticModel.GetTypeInfo(simpleLambda.Body, ct);
                if (bodyType.ConvertedType != null)
                {
                    var namedType = bodyType.ConvertedType as INamedTypeSymbol;
                    if (namedType != null && namedType.Name == "ValueTask")
                    {
                        // Extract T from ValueTask<T>
                        if (namedType.TypeArguments.Length == 1)
                            return GetResultTypeName(namedType.TypeArguments[0]);
                    }
                    return GetResultTypeName(bodyType.ConvertedType);
                }
            }
            else if (lambda is ParenthesizedLambdaExpressionSyntax parenLambda)
            {
                var bodyType = semanticModel.GetTypeInfo(parenLambda.Body, ct);
                if (bodyType.ConvertedType != null)
                {
                    var namedType = bodyType.ConvertedType as INamedTypeSymbol;
                    if (namedType != null && namedType.Name == "ValueTask")
                    {
                        if (namedType.TypeArguments.Length == 1)
                            return GetResultTypeName(namedType.TypeArguments[0]);
                    }
                    return GetResultTypeName(bodyType.ConvertedType);
                }
            }
        }

        return null;
    }

    private static string? GetResultTypeName(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named)
        {
            var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (!fullName.StartsWith("global::System"))
                return fullName;
        }
        return null;
    }

    private static void GenerateSource(
        SourceProductionContext context,
        ImmutableArray<string> types
    )
    {
        if (types.Length == 0)
            return;

        // Emit compile-time diagnostics for route handler return types.
        // This helps developers verify serialization readiness at build time.
        var sb = new StringBuilder();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("// <auto-generated> by PicoWeb.Gen — Route handler return type analysis");
        sb.AppendLine("// Register route handler return types for serialization validation.");
        sb.AppendLine(
            "// Apply [PicoJetson.PicoJsonSerializable] to types below if they need JSON serialization."
        );
        sb.AppendLine("#pragma warning disable CS1591");
        sb.AppendLine();
        sb.AppendLine("namespace PicoWeb.Gen;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Compile-time record of route handler return types.</summary>");
        sb.AppendLine("internal static class RouteReturnTypes");
        sb.AppendLine("{");
        sb.AppendLine(
            "    /// <summary>Types returned by MapGet/MapPost/MapPut/MapDelete handlers.</summary>"
        );
        sb.AppendLine("    internal static readonly System.Type[] Types =");
        sb.AppendLine("        [");

        foreach (var type in types.Distinct(StringComparer.Ordinal))
        {
            var safeTypeName = type.Replace("global::", "").Replace("<", "(").Replace(">", ")");
            sb.AppendLine($"            typeof({type}),");

            // Emit a diagnostic to inform about non-trivial return types
            if (
                !type.StartsWith("global::PicoNode.Http.HttpResponse", StringComparison.Ordinal)
                && !type.StartsWith(
                    "global::System.Threading.Tasks.ValueTask",
                    StringComparison.Ordinal
                )
            )
            {
                context.ReportDiagnostic(
                    Microsoft.CodeAnalysis.Diagnostic.Create(
                        new Microsoft.CodeAnalysis.DiagnosticDescriptor(
                            id: "PWR001",
                            title: "Route handler return type",
                            messageFormat: "Route handler returns '{0}'. Ensure it is serializable if used as JSON response.",
                            category: "PicoWeb",
                            defaultSeverity: Microsoft.CodeAnalysis.DiagnosticSeverity.Info,
                            isEnabledByDefault: true
                        ),
                        location: null,
                        type
                    )
                );
            }
        }

        sb.AppendLine("        ];");
        sb.AppendLine("}");

        context.AddSource("RouteReturnTypes.g.cs", sb.ToString());
    }
}
