global using System.Buffers;
global using System.IO.Compression;
global using System.IO.Pipelines;
global using System.Net;
global using System.Text;
global using PicoDI.Abs;
global using PicoNode.Abs;
global using PicoNode.Http;
global using PicoNode.Web.Internal;
global using PicoNode.Web.Session.Abs;
global using HttpVersion = PicoNode.Http.HttpVersion;
